// Dictionnaire des mots de passe les plus courants (pour simulation d'attaque)
export const COMMON_PASSWORDS = [
  'password',
  '123456',
  '12345678',
  'qwerty',
  'abc123',
  'monkey',
  '1234567',
  'letmein',
  'trustno1',
  'dragon',
  'baseball',
  'iloveyou',
  'master',
  'sunshine',
  'ashley',
  'bailey',
  'shadow',
  '123123',
  '654321',
  'superman',
  'qazwsx',
  'michael',
  'football',
  'welcome',
  'jesus',
  'ninja',
  'mustang',
  'password123',
  'admin',
  'root',
  'admin123',
  'password1',
  'pass',
  'login',
  'admin@123',
  'azerty',
  'azertyuiop',
  'bonjour',
  'francais',
  'soleil',
  'amour',
  'chiffre',
  'complet',
  'internet',
  'securite',
  'ordinateur',
  'clavier',
  'souris',
  'ecran',
  'telephone',
  'maison',
  'voiture',
  'arbre',
  'fleur',
  'animal',
  'couleur',
  'numero',
  'date',
  'heure',
  'jour',
  'mois',
  'annee',
  'saison',
  'temps',
  'meteo',
  'pluie',
  'neige',
  'vent',
  'nuage',
  'soleil2024',
  'password2024',
  'admin2024',
  'welcome123',
  'test123',
  'demo123',
  'qwerty123',
  'abc12345',
  'zxcvbn',
  'asdfgh',
  'qweasd',
  '111111',
  '222222',
  '000000',
  '999999',
  'aaaaaa',
  'gggggg',
  'zzzzzz',
];

// Caractères pour brute force
export const CHARSET_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz';
export const CHARSET_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const CHARSET_DIGITS = '0123456789';
export const CHARSET_SPECIAL = '!@#$%^&*()_+-=[]{}|;:,.<>?';

// Vitesse de test simulée
export const SIMULATED_SPEED = 500000; // tentatives par seconde (CPU)
export const GPU_SPEED = 50000000; // tentatives par seconde (GPU)

// Qualités de mot de passe
export const PASSWORD_QUALITIES = {
  VERY_WEAK: 'very_weak',
  WEAK: 'weak',
  FAIR: 'fair',
  GOOD: 'good',
  STRONG: 'strong',
  VERY_STRONG: 'very_strong',
};

// Entropie minimum par qualité
export const ENTROPY_THRESHOLDS = {
  0: { quality: PASSWORD_QUALITIES.VERY_WEAK, label: 'Très faible', color: '#dc2626' },
  20: { quality: PASSWORD_QUALITIES.WEAK, label: 'Faible', color: '#ea580c' },
  40: { quality: PASSWORD_QUALITIES.FAIR, label: 'Moyen', color: '#f59e0b' },
  60: { quality: PASSWORD_QUALITIES.GOOD, label: 'Bon', color: '#10b981' },
  80: { quality: PASSWORD_QUALITIES.STRONG, label: 'Très bon', color: '#059669' },
  100: { quality: PASSWORD_QUALITIES.VERY_STRONG, label: 'Excellent', color: '#047857' },
};
